// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutWebSite: typeof import('./src/components/about/AboutWebSite.vue')['default']
    BlogArticle: typeof import('./src/components/article/BlogArticle.vue')['default']
    BlogArticleClassification: typeof import('./src/components/article/BlogArticleClassification.vue')['default']
    BlogArticleHistory: typeof import('./src/components/article/BlogArticleHistory.vue')['default']
    BlogBookReview: typeof import('./src/components/life/BlogBookReview.vue')['default']
    BlogFirstScreen: typeof import('./src/components/BlogFirstScreen.vue')['default']
    BlogHome: typeof import('./src/components/BlogHome.vue')['default']
    BlogInformalEssay: typeof import('./src/components/life/BlogInformalEssay.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    TypeWriter: typeof import('./src/components/TypeWriter.vue')['default']
    WebSiteNavigation: typeof import('./src/components/function/WebSiteNavigation.vue')['default']
  }
}
